package ch.wetwer.propagandabot;

/**
 * @author Wetwer
 * @project propaganda-bot
 * @package ch.wetwer.propagandabot
 * @created 12.02.2019
 **/
public class Songs {


    static final String[] BITCH_LASAGNA = new String[]{
            "I don't like you T-Series",
            "Nothing personal, kid",
            "But I must go all out",
            "Just this once",
            "Bobs or vegana, whichever will it be?",
            "Sit the fuck down T-Series",
            "I'm here to spill the real tea",
            "You tryna dethrone me from spot on number one",
            "But you India, you lose",
            "So best think you haven't won",
            "When I'm through with you",
            "We're gonna be completely fucking done",
            "'Cause we only just begun",
            "I review you",
            "Zero",
            "Bye bitch, gone",
            "So come on, T-Series",
            "Looking hungry for some drama",
            "Here, let me serve your bitch lasagna",
            "Bitch, lasagna",
            "Bitch, lasagna",
            "T-Series ain't nothing but a bitch, lasagna",
            "Bitch, lasagna",
            "Bitch, lasagna",
            "Look at T-Series they just crying for their momma",
            "Bitch, lasagna",
            "Bitch, lasagna",
            "T-Series ain't nothing but a bitch, lasagna",
            "Bitch, lasagna",
            "Bitch, lasagna",
            "T-Series just wet themselves in their pajama",
            "So who the hell is Bob, and why you wanna kiss him? (ew)",
            "I'm a blue eyes white dragon, while you're just dark magician (oof)",
            "You got a fifth of the population in your nation but",
            "I got nine-year-olds of worlds so hold your defecation (oops)",
            "Motu Patlu, what the fuck is that even supposed to mean?",
            "Your language sounds like it came from a mumble rap community",
            "No papa, no papa, yes papa, Johnny",
            "Now down all of this sugar and",
            "Let's throw this fucking party with some",
            "Bitch, lasagna",
            "Bitch, lasagna",
            "Look at T-Series they just crying for their momma",
            "Bitch, lasagna",
            "Bitch, lasagna",
            "T-Series ain't nothing but a bitch lasagna",
            "Bitch, lasagna",
            "Bitch, lasagna",
            "Look at T-Series they just wetting their pajama",
            "Bitch, lasagna",
            "Bitch, lasagna",
            "T-Series ain't nothing but a bitch lasagna",
            "You got a population of 1.32 billion",
            "But most your videos can't seem to hit even a million",
            "Sub-bot!",
    };

    static final String[] OHNE_MEIN_TEAM = new String[]{
            "Zu sechst im Mercedes",
            "Weil alle Jungs müssen mit",
            "Ein bisschen Sekt für die Mädels ",
            "Und auf hundert ein' Fick",
            "Kein Gesetz, keine Regel",
            "Lass uns Kohle verdienen",
            "Weil so lässt es sich leben ",
            "Und niemals ohne mein Team",
            "Ich schließe die Tür des Apartments",
            "Wenn die Party komplett ist",
            "Monika, Sarah, Belinda von Instagram auf meine Guestlist",
            "Menthol in der Kippe, Soda im Drink",
            "'Ne Chick will, dass ich für sie „So lala“ sing'",
            "Sie will mich intim",
            "Ich kooperiere nicht ohne mein Team!",
            "Die Sonne scheint durch die Gardine",
            "Hautfarbe Ovomaltine",
            "Kokain in der Kabine zu zweit",
            "Der Tod hat die Todespapiere verteilt",
            "All meine Arabs sind heute Latinos",
            "„¿Chica, qué pasa?“ Die Boys sind amigos",
            "Sie passt mir den Joint, lass' die Homies dran ziehen",
            "Gesmokt wird nie ohne mein Team!",
            "ohne mein Team!",
            "Hamburg, Berlin, West-Wien! (Nie ohne) ohne mein Team!",
            "(Nie ohne) ohne mein Team! (Nie ohne) ohne mein Team!",
            "Hamburg, Berlin, West-Wien! Nie ohne, ohne mein Team!",
            "nicht um zwölf Uhr, aber dreizehn Uhr ist schon okay",
            "(Ein Jahr lang, zwei Jahr lang) ab dreizehn Uhr ist schon okay",
            "(Ein Glas Yamazaki) nicht schon um zwölf, aber eins ist okay",
            "Jeden Tag eine Party",
            "Trete nicht auf, nicht ohne mein Team",
            "Keiner hier nimmt uns die Philosophie",
            "Alles betäubt Lidocain",
            "Frag nicht, wie viel ich am Kilo verdienen",
            "Ein Chick in der Linken, ein Chick in der Rechten",
            "Wir sehen uns beim Echo Liste von Maxwell!",
            "Bring mir den Rum, eine Kiste vom besten",
            "Brauch' kein Hotel, Baby, ficken im Backstage",
            "Was heute passiert, wird morgen verdrängt",
            "Lass' mich am Strand von der Sonne verbrennen",
            "Sie komm' mit den Cops, ich komm' mit der Gang",
            "In Sachen Gewalt sind wir zu konsequent",
            "Alle aus Ghana sind heut' Brasilianer",
            "Prince Boateng von der Copacabana",
            "Koma sein Vater, die Drogen sind clean",
            "Alle wollen mich oben-ohne bedien', doch nie ohne Team!",
            "ohne mein Team!",
            "Hamburg, Berlin, West-Wien! (Nie ohne) ohne mein Team!",
            "(Nie ohne) ohne mein Team! (Nie ohne) ohne mein Team!",
            "Hamburg, Berlin, West-Wien! Nie ohne, ohne mein Team!",
            "nicht um zwölf Uhr, aber dreizehn Uhr ist schon okay",
            "(Ein Jahr lang, zwei Jahr lang) ab dreizehn Uhr ist schon okay",
            "(Ein Glas Yamazaki) nicht schon um zwölf, aber eins ist okay",
            "Jeden Tag eine Party, weil ab dreizehn Uhr ist schon okay",
            "Zu sechst im Mercedes",
            "Weil alle Jungs müssen mit",
            "Ein bisschen Sekt für die Mädels ",
            "Und auf hundert ein' Fick",
            "Kein Gesetz, keine Regel",
            "Lass uns Kohle verdienen",
            "Weil so lässt es sich leben ",
            "Und niemals ohne mein Team",
            "nicht um zwölf Uhr, aber dreizehn Uhr ist schon okay",
            "(Ein Jahr lang, zwei Jahr lang) ab dreizehn Uhr ist schon okay",
            "(Ein Glas Yamazaki) nicht schon um zwölf, aber eins ist okay",
            "Jeden Tag eine Party, weil ab dreizehn Uhr ist schon okay",
            "Hey, hey, hey, hey, hey, hey, hey",
            "Hey, hey, hey, hey, hey, hey, hey",
            "Hey, hey, hey, hey, hey, hey, hey",
            "Hey, hey, hey, hey, hey, hey, hey",
    };
    static final String[] PRIMA_VICTORIA = new String[]{
            "Through the gates of hell",
            "As we make our way to heaven",
            "Through the Nazi lines",
            "Primo victoria",
            "We've been training for years",
            "Now we're ready to strike",
            "As the great operation begins",
            "We're the first wave on the shore",
            "We're the first ones to fall",
            "Yet soldiers have fallen before",
            "In the dawn they will pay",
            "With their lives as the price",
            "History's written today",
            "In this burning inferno",
            "Know that nothing remains",
            "As our forces advance on the beach",
            "Aiming for heaven though serving in hell",
            "Victory is ours their forces will fall",
            "Through the gates of hell",
            "As we make our way to heaven",
            "Through the Nazi lines",
            "Primo victoria",
            "On the 6th of June",
            "On the shores of western Europe 1944",
            "D-day upon us",
            "We've been here before",
            "Used to this kind of war",
            "Crossfire grind through the sand",
            "Our orders were easy",
            "It's kill or be killed",
            "Blood on both sides will be spilled",
            "In the dawn they will pay",
            "With their lives as the price",
            "History's written today",
            "Now that we are at war",
            "With the axis again",
            "This time we know what will come",
            "Aiming for heaven though serving in hell",
            "Victory is ours their forces will fall",
            "Through the gates of hell",
            "As we make our way to heaven",
            "Through the Nazi lines",
            "Primo victoria",
            "On 6th of June",
            "On the shores of western Europe 1944",
            "D-day upon us",
            "6th of June 1944",
            "Allies are turning the war",
            "Normandy state of anarchy",
            "Overlord",
            "Aiming for heaven though serving in hell",
            "Victory is ours their forces will fall",
            "Through the gates of hell",
            "As we make our way to heaven",
            "Through the Nazi lines",
            "Primo victoria",
            "On 6th of June",
            "On the shores of western Europe 1944",
            "D-day upon us",
            "Through the gates of hell",
            "As we make our way to heaven",
            "Through the Nazi lines",
            "Primo victoria",
            "On 6th of June",
            "On the shores of western Europe 1944",
            "Primo victoria",
    };

    static final String[] BASKEN_2017 = new String[]{
            "Der var engang en lille dreng der hed Basken",
            "Han kunne slet ikke lide det musik alle drengene fra skolen hørte",
            "Han ville bare baske til det sygeste døds tramp",
            "Hver dag gik basken hjem fra skole",
            "Hvor han tænkte på at baske nogle fede kællinger med hans kæmpe",
            "Eskimo pølse",
            "Basken to altid i byen alene",
            "Fordi ingen gad at baske med ham",
            "Ude på toilettet jordede han sit gigantiske landkværn",
            "Op i røvfjappen på en fed by trunte",
            "Efter massakren drog han mod DJ'es pult",
            "Hvor han gennembaskede DJ'en med mikrofonen",
            "Til sidst flår han AUX stikket ud og pløjer det ind i",
            "Hans antikke walkman",
            "Der er stille, hvad skal der ske?",
            "En lille smatluder fra dansegulvet er forvirret og råber",
            "Hey hvad fanden sker der her?",
            "Nu har basken taget over",
            "Smid jeres hjerner",
            "Nu har basken taget over",
            "Stop dine fødder ned i dine røjser og kom igang",
            "Basken vågner op nøgen den næste dag på et hotel i Sverige",
            "Med cocain på overlæben og et sugerør i næsen",
            "Hvad er der sket?",
            "Det sidste han husker var da han voldtog en fed betændt skøge",
            "Over puslebordet i en vuggestue",
            "På hylden i værelset står der en",
            "Lille DAB radio som han knap nok kan høre",
            "Han kan lide akkurat høre den bløde bass og de hårde trommer",
            "Byen kalder, Basken slikker overlæben ren for coke",
            "Og puffer en heroin-sprøjte i låret",
            "Nu er han klar",
            "Han bunder en Stroh rom",
            "Og smadrer værelses vinduet med hans enorme pandebrask",
            "Og løber mod det nærmeste diskotek",
            "Alle på dansegulvet kigger op",
            "Der er stille",
            "Hvad skal der ske?",
            "En svensk smatluder fra dansegulvet er forvirret og råber",
            "Hej vad fan händer här? Nu har basken tagit över. kasta dina hjärnor",
            "Fan i helvete",
            "Stop dine fødder ned i dine røjser og kom igang"
    };

    static final String[] BELLA_CIAO = new String[]{
            "Mi son alzato",
            "O bella ciao, bella ciao, bella ciao, ciao, ciao",
            "Una mattina mi son alzato",
            "E ho trovato l'invasor",
            "O partigiano, portami via",
            "O bella ciao, bella ciao, bella ciao, ciao, ciao",
            "O partigiano, portami via",
            "Ché mi sento di morir",
            "O partigiano",
            "Morir",
            "Ciao, ciao",
            "Morir",
            "Bella ciao, ciao, ciao",
            "O partigiano",
            "O partigiano",
            "Bella ciao, ciao, ciao",
            "E se io muoio da partigiano",
            "O bella ciao, bella ciao, bella ciao, ciao, ciao",
            "E se io muoio da partigiano",
            "Tu mi devi seppellir",
            "E seppellire lassù in montagna",
            "O bella ciao, bella ciao, bella ciao, ciao, ciao",
            "E seppellire lassù in montagna",
            "Sotto l'ombra di un bel fior",
            "O partigiano",
            "Morir",
            "Ciao, ciao",
            "Morir",
            "Bella ciao, ciao, ciao",
            "O partigiano",
            "O partigiano"
    };

    static final String[] RUN_THROUGH_THE_JUNGLE = new String[]{
            "Whoa thought it was a nightmare",
            "Lord it was so true",
            "They told me don't go walking slow",
            "The devil's on the loose",
            "Better run through the jungle",
            "Better run through the jungle",
            "Better run through the jungle",
            "Whoa don't look back to see",
            "Thought I heard a rumblin'",
            "Calling to my name",
            "Two hundred million guns are loaded",
            "Satan cries 'take aim'",
            "Better run through the jungle",
            "Better run through the jungle",
            "Better run through the jungle",
            "Whoa don't look back to see",
            "Over on the mountain, thunder magic spoke",
            "Let the people know my wisdom",
            "Fill the land with smoke",
            "Better run through the jungle",
            "Better run through the jungle",
            "Better run through the jungle",
            "Whoa don't look back to see",
    };

    static final String[] HIT_OR_MISS = new String[]{
            "Hit or miss",
            "I guess they never miss, huh?",
            "You got a boyfriend, I bet he doesn't kiss ya",
            "He gon' find another girl and he won't miss ya",
            "He gon' skrrt and hit the dab like Wiz Khalifa",
            "You play with them balls like it's FIFA",
            "You on every level, you're the leader, ooh",
            "You used to work at Whataburger",
            "Now you pop your pussy for the Warner Brothers",
            "(And that bangs, bro)",
            "Shots fired, you're fired",
            "You're washed up, you're retired",
            "Your kitty looks like a flat tire (Eww!)",
            "I bet that your kitty real tired",
            "Perfect!",
    };

    static final String[] NEVER_GIVE_YOU_UP = new String[]{
            "We're no strangers to love",
            "You know the rules and so do I",
            "A full commitment's what I'm thinking of",
            "You wouldn't get this from any other guy",
            "I just wanna tell you how I'm feeling",
            "Gotta make you understand",
            "Never gonna give you up",
            "Never gonna let you down",
            "Never gonna run around and desert you",
            "Never gonna make you cry",
            "Never gonna say goodbye",
            "Never gonna tell a lie and hurt you",
            "We've known each other for so long",
            "Your heart's been aching but you're too shy to say it",
            "Inside we both know what's been going on",
            "We know the game and we're gonna play it",
            "And if you ask me how I'm feeling",
            "Don't tell me you're too blind to see",
            "Never gonna give you up",
            "Never gonna let you down",
            "Never gonna run around and desert you",
            "Never gonna make you cry",
            "Never gonna say goodbye",
            "Never gonna tell a lie and hurt you",
            "Never gonna give you up",
            "Never gonna let you down",
            "Never gonna run around and desert you",
            "Never gonna make you cry",
            "Never gonna say goodbye",
            "Never gonna tell a lie and hurt you",
            "Never gonna give, never gonna give",
            "(Give you up)",
            "(Ooh) Never gonna give, never gonna give",
            "(Give you up)",
            "We've known each other for so long",
            "Your heart's been aching but you're too shy to say it",
            "Inside we both know what's been going on",
            "We know the game and we're gonna play it",
            "I just wanna tell you how I'm feeling",
            "Gotta make you understand",
            "Never gonna give you up",
            "Never gonna let you down",
            "Never gonna run around and desert you",
            "Never gonna make you cry",
            "Never gonna say goodbye",
            "Never gonna tell a lie and hurt you",
            "Never gonna give you up",
            "Never gonna let you down",
            "Never gonna run around and desert you",
            "Never gonna make you cry",
            "Never gonna say goodbye",
            "Never gonna tell a lie and hurt you",
            "Never gonna give you up",
            "Never gonna let you down",
            "Never gonna run around and desert you",
            "Never gonna make you cry",
    };

    static final String[] SALIL_SAVARIM = new String[]{
            "saleelul sawarim nasheedul ubah",
            "wa darbul qitaly tariqul haya",
            "fa baynaq tihamin yubidu tugha",
            "wa kateem musawtim jamilun sadah",
            "saleelul sawarim nasheedul ubah",
            "wa darbul qitaly tariqul haya",
            "fa baynaq tihamin yubidu tugha",
            "wa kateem musawtim jamilun sadah",
            "behi azadini w galal bugha faya qawmi hubu lidarbil kumah",
            "fa ima hayatun tasurul hudah wa ima ma'matun yughighul uda",
            "wa ima ma'matun yughighul uda",
            "saleelul sawarim nasheedul ubah",
            "wa darbul qitaly tariqul haya",
            "fa baynaq tihamin yubidu tugha",
            "wa kateem musawtim jamilun sadah",
            "faqum yaw'faya lidarbin naja lilamdi saweeya nasudul ghuza",
            "wa narfa umajida wa nu'leh jiba abat antadila be ghairil ilah",
            "abat antadila le ghairil ilah",
            "saleelul sawarim nasheedul ubah",
            "wa darbul qitaly tariqul haya",
            "fa baynaq tihamin yubidu tugha",
            "wa kateem musawtim jamilun sadah",
            "il al haqi haya da'ana lewa",
            "li sahil manaya be harbi aydah",
            "faman ma ta'minna fi dan an himah",
            "bi janati khuldin sayaghdu azah",
            "bi janati khuldin sayaghdu azah",
            "saleelul sawarim nasheedul ubah",
            "wa darbul qitaly tariqul haya",
            "fa baynaq tihamin yubidu tugha",
            "wa kateem musawtim jamilun sadah",
            "saleelul sawarim nasheedul ubah",
            "wa darbul qitaly tariqul haya",
            "fa baynaq tihamin yubidu tugha",
            "wa kateem musawtim jamilun sadah",
            "saleelul sawarim",
    };

    static final String[] GUCCI_GANG = new String[]{
            "sure thing nigger",
            "Gucci gang, Gucci gang, Gucci gang, Gucci gang",
            "Gucci gang, Gucci gang, Gucci gang (Gucci gang!)",
            "Spend ten racks on a new chain",
            "My bitch love do cocaine, ooh",
            "I fuck a bitch, I forgot her name",
            "I can't buy a bitch no wedding ring",
            "Rather go and buy Balmains",
            "Gucci gang, Gucci gang, Gucci gang (Gucci gang!)",
            "Gucci gang, Gucci gang, Gucci gang, Gucci gang",
            "Gucci gang, Gucci gang, Gucci gang (Gucci gang!)",
            "Spend ten racks on a new chain",
            "My bitch love do cocaine, ooh",
            "I fuck a bitch, I forgot her name, yeah",
            "I can't buy no bitch no wedding ring",
            "Rather go and buy Balmains, aye",
            "Gucci gang, Gucci gang, Gucci gang",
            "-Lil Peep on the mic yeaa-",
            "My lean cost more than your rent, ooh",
            "Your mama still live in a tent, yeah",
            "Still slanging dope in the jets, huh",
            "Me and my grandma take meds, ooh",
            "None of this shit be new to me",
            "Fucking my teacher, call it tutory",
            "Bought some red bottoms, cost hella Gs",
            "Fuck your airline, fuck your company",
            "Bitch, your breath smell like some cigarettes",
            "I'd rather fuck a bitch from the projects",
            "They kicked me out the plane off a Percocet",
            "Now Lil Pump fly a private jet",
            "Everybody screaming fuck West Jet!",
            "Lil Pump still sell that meth",
            "Hunnid on my wrist sippin on Tech",
            "Fuck a lil bitch, make her pussy wet",
    };
}
